DROP TABLE "AFFECTATION_ENCHERE" CASCADE CONSTRAINTS;
DROP TABLE "VENTE" CASCADE CONSTRAINTS;
DROP TABLE "ENCHERE" CASCADE CONSTRAINTS;
DROP TABLE "CARACTERISTIQUES" CASCADE CONSTRAINTS;
DROP TABLE "PRODUIT" CASCADE CONSTRAINTS;
DROP TABLE "SALLE_VENTE" CASCADE CONSTRAINTS;
DROP TABLE "CATEGORIE_PRODUIT" CASCADE CONSTRAINTS;
DROP TABLE "TYPE_ENCHERE" CASCADE CONSTRAINTS;
DROP TABLE "TYPE_VENTE" CASCADE CONSTRAINTS;
DROP TABLE "UTILISATEUR" CASCADE CONSTRAINTS;


DROP SEQUENCE ID_ENCHERE;
DROP SEQUENCE ID_PRODUIT;
DROP SEQUENCE ID_SALLE_VENTE;
DROP SEQUENCE ID_TYPE_VENTE;
DROP SEQUENCE ID_VENTE;
commit;
