CREATE TABLE "UTILISATEUR"
 (	"EMAIL" VARCHAR2(30 BYTE) NOT NULL ENABLE,
"NOM" VARCHAR2(30 BYTE) NOT NULL ENABLE,
"PRENOM" VARCHAR2(30 BYTE) NOT NULL ENABLE,
"ADRESSE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
 CONSTRAINT "UTILISATEUR_PK" PRIMARY KEY ("EMAIL")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS"  ENABLE
 ) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;


CREATE TABLE "TYPE_VENTE"
 (	"ID_TYPE_VENTE" NUMBER(*,0) NOT NULL ENABLE,
"PRIX_DEPART" NUMBER(*,0) NOT NULL ENABLE,
"DATE_FIN" DATE,
"DATE_DEBUT" DATE NOT NULL ENABLE,
"DATE_FIN_PRO" DATE NOT NULL ENABLE,
 CONSTRAINT "TYPE_VENTE_PK" PRIMARY KEY ("ID_TYPE_VENTE")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS"  ENABLE
 ) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

 COMMENT ON COLUMN "TYPE_VENTE"."DATE_FIN" IS 'date de fin s''il y en a une autrement null
';
 COMMENT ON COLUMN "TYPE_VENTE"."DATE_DEBUT" IS 'date de debut de vente (date d''ajout du produit à la vente)';






 CREATE TABLE "TYPE_ENCHERE"
 (	"ID_TYPE_ENCHERE" NUMBER NOT NULL ENABLE,
"MONTANTE_DESCENDANTE" VARCHAR2(20 BYTE),
"PLUSIEURS_ENCHERES" VARCHAR2(20 BYTE),
"REVOCABLE" VARCHAR2(20 BYTE),
 CONSTRAINT "TYPE_ENCHERE_PK" PRIMARY KEY ("ID_TYPE_ENCHERE")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS"  ENABLE
 ) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

 COMMENT ON COLUMN "TYPE_ENCHERE"."MONTANTE_DESCENDANTE" IS 'Montante si contient qq chose, Si null, alors l''enchère est de type descendante';
 COMMENT ON COLUMN "TYPE_ENCHERE"."PLUSIEURS_ENCHERES" IS 'Si null, alors l''enchère n''accepte pas plusieurs enchères du même utilisateur. Sinon, elle l''accepte ';
 COMMENT ON COLUMN "TYPE_ENCHERE"."REVOCABLE" IS 'Si null, alors l''enchère n''est pas revocable. Sinon, elle l''est .';


 CREATE TABLE "CATEGORIE_PRODUIT"
  (	"NOM_CATEGORIE_PRODUIT" VARCHAR2(20 BYTE) NOT NULL ENABLE,
 "DESCRIPTION" VARCHAR2(100 BYTE),
  CONSTRAINT "CATEGORIE_PRODUIT_PK" PRIMARY KEY ("NOM_CATEGORIE_PRODUIT")
 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 TABLESPACE "USERS"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 TABLESPACE "USERS" ;




 CREATE TABLE "SALLE_VENTE"
 (	"ID_SALLE_VENTE" NUMBER NOT NULL ENABLE,
"NOM_CATEGORIE_PRODUIT" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"ID_TYPE_ENCHERE" NUMBER NOT NULL ENABLE,
 CONSTRAINT "SALLE_VENTE_PK" PRIMARY KEY ("ID_SALLE_VENTE")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS"  ENABLE,
 CONSTRAINT "FK_CATEGORIEPRODUCT" FOREIGN KEY ("NOM_CATEGORIE_PRODUIT")
  REFERENCES  "CATEGORIE_PRODUIT" ("NOM_CATEGORIE_PRODUIT") ON DELETE CASCADE ENABLE,
 CONSTRAINT "FK_TYPEENCHERE" FOREIGN KEY ("ID_TYPE_ENCHERE")
  REFERENCES  "TYPE_ENCHERE" ("ID_TYPE_ENCHERE") ON DELETE CASCADE ENABLE
 ) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;




CREATE TABLE "PRODUIT"
 (	"ID_PRODUIT" NUMBER NOT NULL ENABLE,
"NOM_PRODUIT" VARCHAR2(30 BYTE) NOT NULL ENABLE,
"PRIX_REVIENT" NUMBER DEFAULT 0,
"STOCK" NUMBER DEFAULT 1,
"ID_SALLE_VENTE" NUMBER NOT NULL ENABLE,
 CONSTRAINT "PRODUIT_PK" PRIMARY KEY ("ID_PRODUIT")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS"  ENABLE,
 CONSTRAINT "PRODUIT_CHK1" CHECK (STOCK > -1) DEFERRABLE ENABLE,
 CONSTRAINT "FK_IDSALLEVENTE" FOREIGN KEY ("ID_SALLE_VENTE")
  REFERENCES  "SALLE_VENTE" ("ID_SALLE_VENTE") ON DELETE CASCADE ENABLE
 ) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

 COMMENT ON COLUMN "PRODUIT"."STOCK" IS 'Par défaut il y a un stock de 1.';


 CREATE TABLE "CARACTERISTIQUES"
  (	"CARACTERISTIQUES" VARCHAR2(100 BYTE) NOT NULL ENABLE,
 "ID_PRODUIT" NUMBER NOT NULL ENABLE,
  CONSTRAINT "FK_PRODUIT" FOREIGN KEY ("ID_PRODUIT")
   REFERENCES  "PRODUIT" ("ID_PRODUIT") ON DELETE CASCADE ENABLE
  ) SEGMENT CREATION IMMEDIATE
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 TABLESPACE "USERS" ;


 CREATE TABLE "ENCHERE"
 (	"ID_ENCHERE" NUMBER(*,0) NOT NULL ENABLE,
"PRIX_ACHAT" NUMBER(*,0) NOT NULL ENABLE,
"DATE_ENCHERE" DATE NOT NULL ENABLE,
"QUANTITE" NUMBER(*,0) NOT NULL ENABLE,
 CONSTRAINT "ENCHERE_PK" PRIMARY KEY ("ID_ENCHERE")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS"  ENABLE,
 CONSTRAINT "ENCHERE_CHK1" CHECK (QUANTITE > 0) ENABLE
 ) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;


CREATE TABLE "VENTE"
 (	"ID_VENTE" NUMBER(*,0) NOT NULL ENABLE,
"ID_TYPE_VENTE" NUMBER(*,0) NOT NULL ENABLE,
"ID_PRODUIT" NUMBER NOT NULL ENABLE,
 CONSTRAINT "VENTE_PK" PRIMARY KEY ("ID_VENTE")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS"  ENABLE,
 CONSTRAINT "FK_TYPEVENTE" FOREIGN KEY ("ID_TYPE_VENTE")
  REFERENCES  "TYPE_VENTE" ("ID_TYPE_VENTE") ON DELETE CASCADE ENABLE,
 CONSTRAINT "FK_ID_PRODUIT" FOREIGN KEY ("ID_PRODUIT")
  REFERENCES  "PRODUIT" ("ID_PRODUIT") ON DELETE CASCADE ENABLE
 ) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;



CREATE TABLE "AFFECTATION_ENCHERE"
 (	"EMAIL" VARCHAR2(30 BYTE) NOT NULL ENABLE,
"ID_ENCHERE" NUMBER NOT NULL ENABLE,
"ID_VENTE" NUMBER NOT NULL ENABLE,
 CONSTRAINT "AFFECTATION_ENCHERE_PK" PRIMARY KEY ("EMAIL", "ID_ENCHERE", "ID_VENTE")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS"  ENABLE,
 CONSTRAINT "FK_EMAIL" FOREIGN KEY ("EMAIL")
  REFERENCES  "UTILISATEUR" ("EMAIL") ON DELETE CASCADE ENABLE,
 CONSTRAINT "FK_ID_ENCHERE" FOREIGN KEY ("ID_ENCHERE")
  REFERENCES  "ENCHERE" ("ID_ENCHERE") ON DELETE CASCADE ENABLE,
 CONSTRAINT "FK_ID_VENTE" FOREIGN KEY ("ID_VENTE")
  REFERENCES  "VENTE" ("ID_VENTE") ON DELETE CASCADE ENABLE
 ) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;



--les 5 sequence permettant de generer les differents id dans plusieurs tables

CREATE SEQUENCE  "ID_ENCHERE"  MINVALUE 10 MAXVALUE 99999999 INCREMENT BY 1 START WITH 181 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

CREATE SEQUENCE  "ID_PRODUIT"  MINVALUE 20 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

CREATE SEQUENCE  "ID_SALLE_VENTE"  MINVALUE 10 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

CREATE SEQUENCE  "ID_TYPE_VENTE"  MINVALUE 10 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

CREATE SEQUENCE  "ID_VENTE"  MINVALUE 20 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
